server:
  port:8001

# mybatis配置
mybatis:
  type-aliases-package: com.laoxuan.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
#  mybatis的路径配置
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置，配置启动什么项目
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #org.gjt.mm.mysql.Driver com.mysql.jdbc.Driver
    driver-class-name: org.gjt.mm.mysql.Driver
    #url: jdbc:mysql://localhost:3306/db01?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root